find_package(PCL 1.7 REQUIRED)
add_library(pcl-common STATIC IMPORTED)
set_property(TARGET pcl-common PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-common PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-common PROPERTY 
	IMPORTED_LOCATION ${PCL_COMMON_LIBRARIES})

add_library(pcl-octree STATIC IMPORTED)
set_property(TARGET pcl-octree PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-octree PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-octree PROPERTY 
	IMPORTED_LOCATION ${PCL_OCTREE_LIBRARIES})

add_library(pcl-io STATIC IMPORTED)
set_property(TARGET pcl-io PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-io PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-io PROPERTY 
	IMPORTED_LOCATION ${PCL_IO_LIBRARIES})

add_library(pcl-kdtree STATIC IMPORTED)
set_property(TARGET pcl-kdtree PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-kdtree PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-kdtree PROPERTY 
	IMPORTED_LOCATION ${PCL_KDTREE_LIBRARIES})

add_library(pcl-search STATIC IMPORTED)
set_property(TARGET pcl-search PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-search PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-search PROPERTY 
	IMPORTED_LOCATION ${PCL_SEARCH_LIBRARIES})
	
add_library(pcl-sample-consensus STATIC IMPORTED)
set_property(TARGET pcl-sample-consensus PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-sample-consensus PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-sample-consensus PROPERTY 
	IMPORTED_LOCATION ${PCL_SAMPLE_CONSENSUS_LIBRARIES})

add_library(pcl-filters STATIC IMPORTED)
set_property(TARGET pcl-filters PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-filters PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-filters PROPERTY 
	IMPORTED_LOCATION ${PCL_FILTERS_LIBRARIES})

add_library(pcl-2d STATIC IMPORTED)
set_property(TARGET pcl-2d PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-2d PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-2d PROPERTY 
	IMPORTED_LOCATION ${PCL_2D_LIBRARIES})

add_library(pcl-geometry STATIC IMPORTED)
set_property(TARGET pcl-geometry PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-geometry PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-geometry PROPERTY 
	IMPORTED_LOCATION ${PCL_GEOMETRY_LIBRARIES})

add_library(pcl-features STATIC IMPORTED)
set_property(TARGET pcl-features PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-features PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-features PROPERTY 
	IMPORTED_LOCATION ${PCL_FEATURES_LIBRARIES})

add_library(pcl-ml STATIC IMPORTED)
set_property(TARGET pcl-ml PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-ml PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-ml PROPERTY 
	IMPORTED_LOCATION ${PCL_ML_LIBRARIES})

add_library(pcl-segmentation STATIC IMPORTED)
set_property(TARGET pcl-segmentation PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-segmentation PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-segmentation PROPERTY 
	IMPORTED_LOCATION ${PCL_SEGMENTATION_LIBRARIES})

add_library(pcl-visualization STATIC IMPORTED)
set_property(TARGET pcl-visualization PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-visualization PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-visualization PROPERTY 
	IMPORTED_LOCATION ${PCL_VISUALIZATION_LIBRARIES})

add_library(pcl-surface STATIC IMPORTED)
set_property(TARGET pcl-surface PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-surface PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-surface PROPERTY 
	IMPORTED_LOCATION ${PCL_SURFACE_LIBRARIES})

add_library(pcl-registration STATIC IMPORTED)
set_property(TARGET pcl-registration PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-registration PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-registration PROPERTY 
	IMPORTED_LOCATION ${PCL_REGISTRATION_LIBRARIES})

add_library(pcl-keypoints STATIC IMPORTED)
set_property(TARGET pcl-keypoints PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-keypoints PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-keypoints PROPERTY 
	IMPORTED_LOCATION ${PCL_KEYPOINTS_LIBRARIES})

add_library(pcl-tracking STATIC IMPORTED)
set_property(TARGET pcl-tracking PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-tracking PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-tracking PROPERTY 
	IMPORTED_LOCATION ${PCL_TRACKING_LIBRARIES})

add_library(pcl-recognition STATIC IMPORTED)
set_property(TARGET pcl-recognition PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-recognition PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-recognition PROPERTY 
	IMPORTED_LOCATION ${PCL_RECOGNITION_LIBRARIES})

add_library(pcl-stereo STATIC IMPORTED)
set_property(TARGET pcl-stereo PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-stereo PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-stereo PROPERTY 
	IMPORTED_LOCATION ${PCL_STEREO_LIBRARIES})

add_library(pcl-outofcore STATIC IMPORTED)
set_property(TARGET pcl-outofcore PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-outofcore PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-outofcore PROPERTY 
	IMPORTED_LOCATION ${PCL_OUTOFCORE_LIBRARIES})
	
add_library(pcl-people STATIC IMPORTED)
set_property(TARGET pcl-people PROPERTY
    INTERFACE_INCLUDE_DIRECTORIES ${PCL_INCLUDE_DIRS})
set_property(TARGET pcl-people PROPERTY
	INTERFACE_COMPILE_DEFINITIONS ${PCL_DEFINITIONS})
set_property(TARGET pcl-people PROPERTY 
	IMPORTED_LOCATION ${PCL_PEOPLE_LIBRARIES})
	




	
	